# Generated by Django 3.2.4 on 2021-06-14 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import micro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bio', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ocurrencies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('publishermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='micro.publishermodel')),
                ('apiKey', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(50)])),
            ],
            bases=('micro.publishermodel',),
        ),
        migrations.CreateModel(
            name='PublicMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='author', to='micro.publishermodel')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions', to='micro.PublisherModel')),
                ('tags', models.ManyToManyField(blank=True, to='micro.TagModel')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=250)),
                ('destination', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='destination', to='micro.publishermodel')),
                ('source', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='source', to='micro.publishermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('publishermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='micro.publishermodel')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birthday', models.DateField(blank=True)),
                ('follows', models.ManyToManyField(blank=True, through='micro.FollowRelationship', to='micro.UserModel')),
            ],
            bases=('micro.publishermodel',),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='from_user',
            field=models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='from_user', to='micro.usermodel'),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='to_user',
            field=models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='to_user', to='micro.usermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='followrelationship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
