# Generated by Django 3.1.7 on 2021-07-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
