# Generated by Django 3.2.3 on 2021-05-21 11:35

from django.db import migrations, models
import micro.models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ocurrencies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='author', to='micro.publishermodel')),
                ('mentions', models.ManyToManyField(related_name='mentions', to='micro.PublisherModel')),
                ('tags', models.ManyToManyField(to='micro.TagModel')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='from_user', to='micro.usermodel')),
                ('to_user', models.ForeignKey(on_delete=models.SET(micro.models.get_sentinel_user), related_name='to_user', to='micro.usermodel')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='follows',
            field=models.ManyToManyField(through='micro.FollowRelationship', to='micro.UserModel'),
        ),
    ]
