# Generated by Django 3.2.3 on 2021-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_auto_20210521_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmessagemodel',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions', to='micro.PublisherModel'),
        ),
        migrations.AlterField(
            model_name='publicmessagemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='micro.TagModel'),
        ),
        migrations.AlterField(
            model_name='publishermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='follows',
            field=models.ManyToManyField(blank=True, through='micro.FollowRelationship', to='micro.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
